api_user_list:
    path:  /
    defaults: { _controller: AskerBundle:Api/User/User:list }
    methods: [GET]
    requirements:
        _format: json

api_user_view:
    path:  /{userId}
    defaults: { _controller: AskerBundle:Api/User/User:view }
    methods: [GET]
    requirements:
        _format: json
        userId: \d+
